### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by imkr-vishal**
Added auto server_count_post function.

Function name:
    auto_post_stats

### CODE REVIEW

**Comment by Scientific-Guy** [comment]
Actually its pointless to put the client in `Client` class, its better to make a seperate class coz if some user, just wants to get bot info, he needs to put the `Discord Client` which is madness so on `auto_post_stats` return a class 

https://github.com/listcordteam/listcord.py/blob/204ce7c94bb7d2164bd74401a946d24d4f0a1923/listcord/__init__.py#L13

**Comment by imkr-vishal** [comment]
Its not pointless i pass bot = None by default and used "self.bot.user.id" only in post functions so if someone wants to use get_informations only then he can simply just pass the token nothing more.

**Comment by imkr-vishal** [comment]
And also "len(self.bot.guilds)" in post functions will avoid users to upload fake server_counts..

**Comment by Scientific-Guy** [comment]
Ok see if its really then the type should be `Optional[Discord.Client]` and the bot param should be after the token parameter

https://github.com/listcordteam/listcord.py/blob/204ce7c94bb7d2164bd74401a946d24d4f0a1923/listcord/__init__.py#L12

And it would be completely madness if the user wants to make a non discord related program and use the pkg and get the `discord.py` imported which is also pointless...

And `len(self.bot.guilds)`, see auto poster is made to do post server counts in real lmao! Secondly u see auto poster doesnt means posting server count once, it means posting it automatically once for 20 minutes...

i mean create a AutoPoster class for auto poster dont use client itself...

**Pull request closed without merging**
